# This is a basic workflow to help you get started with Actions

name: Docker Build & Push

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Build & Push
        uses: craftech-io/package-action@v3.1.0
        with:
          # GitHub Repository Token to log in using.
          access_token: ${{ secrets.GITHUB_TOKEN }}
          # Where should GitHub Docker find the Dockerfile, relative to the root of the repository.
          context: /app/Dockerfile
